#ifndef __DISPLAY_H
#define __DISPLAY_H
#include "User_Def.h"

#define LCD_IO_1	P27D
#define LCD_IO_2	P26D
#define LCD_IO_3	P25D
#define LCD_IO_4	P24D
#define LCD_IO_5	P23D
#define LCD_IO_6	P22D
#define KEY_IO		P00D
#define COLD		P15D
#define MOTO		P14D

#define IO1_IN	P27_INPUTHIZ_MODE
#define IO1_OUT	P27_PUSHPULL_MODE
#define IO2_IN	P26_INPUTHIZ_MODE
#define IO2_OUT	P26_PUSHPULL_MODE
#define IO3_IN	P25_INPUTHIZ_MODE
#define IO3_OUT	P25_PUSHPULL_MODE
#define IO4_IN	P24_INPUTHIZ_MODE
#define IO4_OUT	P24_PUSHPULL_MODE
#define IO5_IN	P23_INPUTHIZ_MODE
#define IO5_OUT	P23_PUSHPULL_MODE
#define IO6_IN	P22_INPUTHIZ_MODE
#define IO6_OUT	P22_PUSHPULL_MODE
#define LCD_ALL_OUT				IO1_OUT;  IO2_OUT;  IO3_OUT;  IO4_OUT;  IO5_OUT;  IO6_OUT;
#define LCD_ALL_IN				IO1_IN; IO2_IN;  IO3_IN;  IO4_IN;  IO5_IN;  IO6_IN;
#define LCD_SHANG1_MODE	 	 	IO2_OUT;  IO3_OUT;	LCD_SHANG1
#define LCD_YOUSHANG1_MODE	 	IO2_OUT;  IO4_OUT;	LCD_YOUSHANG1
#define LCD_YOUXIA1_MODE	 	IO2_OUT; IO5_OUT;	LCD_YOUXIA1
#define LCD_XIA1_MODE	 		IO2_OUT;  IO6_OUT;	LCD_XIA1
#define LCD_ZUOXIA1_MODE	 	IO2_OUT;  IO5_OUT; 	LCD_ZUOXIA1
#define LCD_ZUOSHANG1_MODE	 	IO2_OUT;  IO3_OUT; 	LCD_ZUOSHANG1
#define LCD_ZHONG1_MODE	 		IO2_OUT;   IO4_OUT;	LCD_ZHONG1
#define LCD_OP1_MODE	 		IO1_OUT; IO2_OUT; 	LCD_OP1

#define LCD_SHANG1			LCD_IO_2 = NUM_DISABLE; LCD_IO_3 = NUM_ENABLE
#define LCD_YOUSHANG1		LCD_IO_2 = NUM_DISABLE; LCD_IO_4 = NUM_ENABLE
#define LCD_YOUXIA1			LCD_IO_5 = NUM_DISABLE; LCD_IO_2 = NUM_ENABLE
#define LCD_XIA1			LCD_IO_2 = NUM_DISABLE; LCD_IO_6 = NUM_ENABLE
#define LCD_ZUOXIA1			LCD_IO_2 = NUM_DISABLE; LCD_IO_5 = NUM_ENABLE
#define LCD_ZUOSHANG1		LCD_IO_3 = NUM_DISABLE; LCD_IO_2 = NUM_ENABLE
#define LCD_ZHONG1			LCD_IO_4 = NUM_DISABLE; LCD_IO_2 = NUM_ENABLE
#define LCD_OP1				LCD_IO_2 = NUM_DISABLE; LCD_IO_1 = NUM_ENABLE

#define LCD_SHANG2_MODE	 		IO4_OUT;  	IO5_OUT;	LCD_SHANG2
#define LCD_YOUSHANG2_MODE	 	IO3_OUT;  	IO5_OUT; 	LCD_YOUSHANG2
#define LCD_YOUXIA2_MODE	 	IO4_OUT;  	IO5_OUT;	LCD_YOUXIA2
#define LCD_XIA2_MODE	 		IO3_OUT;  	IO4_OUT;	LCD_XIA2
#define LCD_ZUOXIA2_MODE	 	IO3_OUT;  	IO6_OUT;	LCD_ZUOXIA2
#define LCD_ZUOSHANG2_MODE	 	IO3_OUT;   	IO4_OUT;	LCD_ZUOSHANG2
#define LCD_ZHONG2_MODE	 		IO3_OUT;  	IO5_OUT;	LCD_ZHONG2
#define LCD_OP2_MODE	 		IO1_OUT; 	IO3_OUT;  	LCD_OP2


#define LCD_SHANG2			LCD_IO_5 = NUM_DISABLE; LCD_IO_4 = NUM_ENABLE
#define LCD_YOUSHANG2		LCD_IO_3 = NUM_DISABLE; LCD_IO_5 = NUM_ENABLE
#define LCD_YOUXIA2			LCD_IO_4 = NUM_DISABLE; LCD_IO_5 = NUM_ENABLE
#define LCD_XIA2			LCD_IO_3 = NUM_DISABLE; LCD_IO_4 = NUM_ENABLE
#define LCD_ZUOXIA2			LCD_IO_6 = NUM_DISABLE; LCD_IO_3 = NUM_ENABLE
#define LCD_ZUOSHANG2		LCD_IO_4 = NUM_DISABLE; LCD_IO_3 = NUM_ENABLE
#define LCD_ZHONG2			LCD_IO_5 = NUM_DISABLE; LCD_IO_3 = NUM_ENABLE
#define LCD_OP2				LCD_IO_3 = NUM_DISABLE; LCD_IO_1 = NUM_ENABLE

#define LCD_SHANG3_MODE	 		IO1_OUT;	IO6_OUT;	LCD_SHANG3
#define LCD_YOUSHANG3_MODE	 	IO3_OUT;	IO6_OUT;	LCD_YOUSHANG3
#define LCD_YOUXIA3_MODE	 	IO5_OUT; 	IO6_OUT;	LCD_YOUXIA3
#define LCD_XIA3_MODE	 		IO4_OUT; 	IO6_OUT;	LCD_XIA3
#define LCD_ZUOXIA3_MODE	 	IO4_OUT; 	IO6_OUT;	LCD_ZUOXIA3
#define LCD_ZUOSHANG3_MODE	 	IO5_OUT;  	IO6_OUT;	LCD_ZUOSHANG3
#define LCD_ZHONG3_MODE	 		IO1_OUT;	IO5_OUT;	LCD_ZHONG3


#define LCD_SHANG3			LCD_IO_1 = NUM_DISABLE; LCD_IO_6 = NUM_ENABLE
#define LCD_YOUSHANG3		LCD_IO_3 = NUM_DISABLE; LCD_IO_6 = NUM_ENABLE
#define LCD_YOUXIA3			LCD_IO_5 = NUM_DISABLE; LCD_IO_6 = NUM_ENABLE
#define LCD_XIA3			LCD_IO_6 = NUM_DISABLE; LCD_IO_4 = NUM_ENABLE
#define LCD_ZUOXIA3			LCD_IO_4 = NUM_DISABLE; LCD_IO_6 = NUM_ENABLE
#define LCD_ZUOSHANG3		LCD_IO_6 = NUM_DISABLE; LCD_IO_5 = NUM_ENABLE
#define LCD_ZHONG3			LCD_IO_1 = NUM_DISABLE; LCD_IO_5 = NUM_ENABLE


typedef enum
{
        NUM_DISABLE,
        NUM_ENABLE
}NUM_TYPE;

typedef enum
{
        IO_1,
        IO_2,
        IO_3,
        IO_4,
        IO_5,
        IO_6,
        IO_MAX
}IO_TYPE;

#endif
